################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (10.3-2021.10)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
../eigen-3.4.0/unsupported/test/BVH.cpp \
../eigen-3.4.0/unsupported/test/EulerAngles.cpp \
../eigen-3.4.0/unsupported/test/FFT.cpp \
../eigen-3.4.0/unsupported/test/FFTW.cpp \
../eigen-3.4.0/unsupported/test/NonLinearOptimization.cpp \
../eigen-3.4.0/unsupported/test/NumericalDiff.cpp \
../eigen-3.4.0/unsupported/test/alignedvector3.cpp \
../eigen-3.4.0/unsupported/test/autodiff.cpp \
../eigen-3.4.0/unsupported/test/autodiff_scalar.cpp \
../eigen-3.4.0/unsupported/test/bessel_functions.cpp \
../eigen-3.4.0/unsupported/test/cxx11_eventcount.cpp \
../eigen-3.4.0/unsupported/test/cxx11_maxsizevector.cpp \
../eigen-3.4.0/unsupported/test/cxx11_meta.cpp \
../eigen-3.4.0/unsupported/test/cxx11_non_blocking_thread_pool.cpp \
../eigen-3.4.0/unsupported/test/cxx11_runqueue.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_argmax.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_argmax_sycl.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_assign.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_block_access.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_block_eval.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_block_io.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_broadcast_sycl.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_broadcasting.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_builtins_sycl.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_casts.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_chipping.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_chipping_sycl.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_comparisons.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_concatenation.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_concatenation_sycl.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_const.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_contract_sycl.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_contraction.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_convolution.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_convolution_sycl.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_custom_index.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_custom_op.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_custom_op_sycl.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_device_sycl.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_dimension.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_empty.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_executor.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_expr.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_fft.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_fixed_size.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_forced_eval.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_forced_eval_sycl.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_generator.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_generator_sycl.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_ifft.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_image_op_sycl.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_image_patch.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_image_patch_sycl.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_index_list.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_inflation.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_inflation_sycl.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_intdiv.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_io.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_layout_swap.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_layout_swap_sycl.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_lvalue.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_map.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_math.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_math_sycl.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_mixed_indices.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_morphing.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_morphing_sycl.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_move.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_notification.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_of_complex.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_of_const_values.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_of_strings.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_padding.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_padding_sycl.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_patch.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_patch_sycl.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_random.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_random_sycl.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_reduction.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_reduction_sycl.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_ref.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_reverse.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_reverse_sycl.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_roundings.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_scan.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_scan_sycl.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_shuffling.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_shuffling_sycl.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_simple.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_striding.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_striding_sycl.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_sugar.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_sycl.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_symmetry.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_thread_local.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_thread_pool.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_trace.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_uint128.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_volume_patch.cpp \
../eigen-3.4.0/unsupported/test/cxx11_tensor_volume_patch_sycl.cpp \
../eigen-3.4.0/unsupported/test/dgmres.cpp \
../eigen-3.4.0/unsupported/test/forward_adolc.cpp \
../eigen-3.4.0/unsupported/test/gmres.cpp \
../eigen-3.4.0/unsupported/test/idrs.cpp \
../eigen-3.4.0/unsupported/test/kronecker_product.cpp \
../eigen-3.4.0/unsupported/test/levenberg_marquardt.cpp \
../eigen-3.4.0/unsupported/test/matrix_exponential.cpp \
../eigen-3.4.0/unsupported/test/matrix_function.cpp \
../eigen-3.4.0/unsupported/test/matrix_power.cpp \
../eigen-3.4.0/unsupported/test/matrix_square_root.cpp \
../eigen-3.4.0/unsupported/test/minres.cpp \
../eigen-3.4.0/unsupported/test/mpreal_support.cpp \
../eigen-3.4.0/unsupported/test/openglsupport.cpp \
../eigen-3.4.0/unsupported/test/polynomialsolver.cpp \
../eigen-3.4.0/unsupported/test/polynomialutils.cpp \
../eigen-3.4.0/unsupported/test/sparse_extra.cpp \
../eigen-3.4.0/unsupported/test/special_functions.cpp \
../eigen-3.4.0/unsupported/test/special_packetmath.cpp \
../eigen-3.4.0/unsupported/test/splines.cpp 

OBJS += \
./eigen-3.4.0/unsupported/test/BVH.o \
./eigen-3.4.0/unsupported/test/EulerAngles.o \
./eigen-3.4.0/unsupported/test/FFT.o \
./eigen-3.4.0/unsupported/test/FFTW.o \
./eigen-3.4.0/unsupported/test/NonLinearOptimization.o \
./eigen-3.4.0/unsupported/test/NumericalDiff.o \
./eigen-3.4.0/unsupported/test/alignedvector3.o \
./eigen-3.4.0/unsupported/test/autodiff.o \
./eigen-3.4.0/unsupported/test/autodiff_scalar.o \
./eigen-3.4.0/unsupported/test/bessel_functions.o \
./eigen-3.4.0/unsupported/test/cxx11_eventcount.o \
./eigen-3.4.0/unsupported/test/cxx11_maxsizevector.o \
./eigen-3.4.0/unsupported/test/cxx11_meta.o \
./eigen-3.4.0/unsupported/test/cxx11_non_blocking_thread_pool.o \
./eigen-3.4.0/unsupported/test/cxx11_runqueue.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_argmax.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_argmax_sycl.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_assign.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_block_access.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_block_eval.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_block_io.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_broadcast_sycl.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_broadcasting.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_builtins_sycl.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_casts.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_chipping.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_chipping_sycl.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_comparisons.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_concatenation.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_concatenation_sycl.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_const.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_contract_sycl.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_contraction.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_convolution.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_convolution_sycl.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_custom_index.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_custom_op.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_custom_op_sycl.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_device_sycl.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_dimension.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_empty.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_executor.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_expr.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_fft.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_fixed_size.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_forced_eval.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_forced_eval_sycl.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_generator.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_generator_sycl.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_ifft.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_image_op_sycl.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_image_patch.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_image_patch_sycl.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_index_list.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_inflation.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_inflation_sycl.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_intdiv.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_io.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_layout_swap.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_layout_swap_sycl.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_lvalue.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_map.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_math.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_math_sycl.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_mixed_indices.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_morphing.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_morphing_sycl.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_move.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_notification.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_of_complex.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_of_const_values.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_of_strings.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_padding.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_padding_sycl.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_patch.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_patch_sycl.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_random.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_random_sycl.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_reduction.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_reduction_sycl.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_ref.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_reverse.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_reverse_sycl.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_roundings.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_scan.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_scan_sycl.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_shuffling.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_shuffling_sycl.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_simple.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_striding.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_striding_sycl.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_sugar.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_sycl.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_symmetry.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_thread_local.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_thread_pool.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_trace.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_uint128.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_volume_patch.o \
./eigen-3.4.0/unsupported/test/cxx11_tensor_volume_patch_sycl.o \
./eigen-3.4.0/unsupported/test/dgmres.o \
./eigen-3.4.0/unsupported/test/forward_adolc.o \
./eigen-3.4.0/unsupported/test/gmres.o \
./eigen-3.4.0/unsupported/test/idrs.o \
./eigen-3.4.0/unsupported/test/kronecker_product.o \
./eigen-3.4.0/unsupported/test/levenberg_marquardt.o \
./eigen-3.4.0/unsupported/test/matrix_exponential.o \
./eigen-3.4.0/unsupported/test/matrix_function.o \
./eigen-3.4.0/unsupported/test/matrix_power.o \
./eigen-3.4.0/unsupported/test/matrix_square_root.o \
./eigen-3.4.0/unsupported/test/minres.o \
./eigen-3.4.0/unsupported/test/mpreal_support.o \
./eigen-3.4.0/unsupported/test/openglsupport.o \
./eigen-3.4.0/unsupported/test/polynomialsolver.o \
./eigen-3.4.0/unsupported/test/polynomialutils.o \
./eigen-3.4.0/unsupported/test/sparse_extra.o \
./eigen-3.4.0/unsupported/test/special_functions.o \
./eigen-3.4.0/unsupported/test/special_packetmath.o \
./eigen-3.4.0/unsupported/test/splines.o 

CPP_DEPS += \
./eigen-3.4.0/unsupported/test/BVH.d \
./eigen-3.4.0/unsupported/test/EulerAngles.d \
./eigen-3.4.0/unsupported/test/FFT.d \
./eigen-3.4.0/unsupported/test/FFTW.d \
./eigen-3.4.0/unsupported/test/NonLinearOptimization.d \
./eigen-3.4.0/unsupported/test/NumericalDiff.d \
./eigen-3.4.0/unsupported/test/alignedvector3.d \
./eigen-3.4.0/unsupported/test/autodiff.d \
./eigen-3.4.0/unsupported/test/autodiff_scalar.d \
./eigen-3.4.0/unsupported/test/bessel_functions.d \
./eigen-3.4.0/unsupported/test/cxx11_eventcount.d \
./eigen-3.4.0/unsupported/test/cxx11_maxsizevector.d \
./eigen-3.4.0/unsupported/test/cxx11_meta.d \
./eigen-3.4.0/unsupported/test/cxx11_non_blocking_thread_pool.d \
./eigen-3.4.0/unsupported/test/cxx11_runqueue.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_argmax.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_argmax_sycl.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_assign.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_block_access.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_block_eval.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_block_io.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_broadcast_sycl.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_broadcasting.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_builtins_sycl.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_casts.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_chipping.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_chipping_sycl.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_comparisons.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_concatenation.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_concatenation_sycl.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_const.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_contract_sycl.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_contraction.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_convolution.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_convolution_sycl.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_custom_index.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_custom_op.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_custom_op_sycl.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_device_sycl.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_dimension.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_empty.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_executor.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_expr.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_fft.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_fixed_size.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_forced_eval.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_forced_eval_sycl.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_generator.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_generator_sycl.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_ifft.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_image_op_sycl.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_image_patch.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_image_patch_sycl.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_index_list.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_inflation.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_inflation_sycl.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_intdiv.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_io.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_layout_swap.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_layout_swap_sycl.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_lvalue.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_map.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_math.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_math_sycl.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_mixed_indices.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_morphing.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_morphing_sycl.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_move.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_notification.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_of_complex.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_of_const_values.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_of_strings.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_padding.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_padding_sycl.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_patch.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_patch_sycl.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_random.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_random_sycl.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_reduction.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_reduction_sycl.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_ref.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_reverse.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_reverse_sycl.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_roundings.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_scan.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_scan_sycl.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_shuffling.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_shuffling_sycl.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_simple.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_striding.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_striding_sycl.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_sugar.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_sycl.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_symmetry.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_thread_local.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_thread_pool.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_trace.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_uint128.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_volume_patch.d \
./eigen-3.4.0/unsupported/test/cxx11_tensor_volume_patch_sycl.d \
./eigen-3.4.0/unsupported/test/dgmres.d \
./eigen-3.4.0/unsupported/test/forward_adolc.d \
./eigen-3.4.0/unsupported/test/gmres.d \
./eigen-3.4.0/unsupported/test/idrs.d \
./eigen-3.4.0/unsupported/test/kronecker_product.d \
./eigen-3.4.0/unsupported/test/levenberg_marquardt.d \
./eigen-3.4.0/unsupported/test/matrix_exponential.d \
./eigen-3.4.0/unsupported/test/matrix_function.d \
./eigen-3.4.0/unsupported/test/matrix_power.d \
./eigen-3.4.0/unsupported/test/matrix_square_root.d \
./eigen-3.4.0/unsupported/test/minres.d \
./eigen-3.4.0/unsupported/test/mpreal_support.d \
./eigen-3.4.0/unsupported/test/openglsupport.d \
./eigen-3.4.0/unsupported/test/polynomialsolver.d \
./eigen-3.4.0/unsupported/test/polynomialutils.d \
./eigen-3.4.0/unsupported/test/sparse_extra.d \
./eigen-3.4.0/unsupported/test/special_functions.d \
./eigen-3.4.0/unsupported/test/special_packetmath.d \
./eigen-3.4.0/unsupported/test/splines.d 


# Each subdirectory must supply rules for building sources it contributes
eigen-3.4.0/unsupported/test/%.o eigen-3.4.0/unsupported/test/%.su: ../eigen-3.4.0/unsupported/test/%.cpp eigen-3.4.0/unsupported/test/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -c -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include/ -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core_A/Include/ -I../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Include -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -Ofast -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-eigen-2d-3-2e-4-2e-0-2f-unsupported-2f-test

clean-eigen-2d-3-2e-4-2e-0-2f-unsupported-2f-test:
	-$(RM) ./eigen-3.4.0/unsupported/test/BVH.d ./eigen-3.4.0/unsupported/test/BVH.o ./eigen-3.4.0/unsupported/test/BVH.su ./eigen-3.4.0/unsupported/test/EulerAngles.d ./eigen-3.4.0/unsupported/test/EulerAngles.o ./eigen-3.4.0/unsupported/test/EulerAngles.su ./eigen-3.4.0/unsupported/test/FFT.d ./eigen-3.4.0/unsupported/test/FFT.o ./eigen-3.4.0/unsupported/test/FFT.su ./eigen-3.4.0/unsupported/test/FFTW.d ./eigen-3.4.0/unsupported/test/FFTW.o ./eigen-3.4.0/unsupported/test/FFTW.su ./eigen-3.4.0/unsupported/test/NonLinearOptimization.d ./eigen-3.4.0/unsupported/test/NonLinearOptimization.o ./eigen-3.4.0/unsupported/test/NonLinearOptimization.su ./eigen-3.4.0/unsupported/test/NumericalDiff.d ./eigen-3.4.0/unsupported/test/NumericalDiff.o ./eigen-3.4.0/unsupported/test/NumericalDiff.su ./eigen-3.4.0/unsupported/test/alignedvector3.d ./eigen-3.4.0/unsupported/test/alignedvector3.o ./eigen-3.4.0/unsupported/test/alignedvector3.su ./eigen-3.4.0/unsupported/test/autodiff.d ./eigen-3.4.0/unsupported/test/autodiff.o ./eigen-3.4.0/unsupported/test/autodiff.su ./eigen-3.4.0/unsupported/test/autodiff_scalar.d ./eigen-3.4.0/unsupported/test/autodiff_scalar.o ./eigen-3.4.0/unsupported/test/autodiff_scalar.su ./eigen-3.4.0/unsupported/test/bessel_functions.d ./eigen-3.4.0/unsupported/test/bessel_functions.o ./eigen-3.4.0/unsupported/test/bessel_functions.su ./eigen-3.4.0/unsupported/test/cxx11_eventcount.d ./eigen-3.4.0/unsupported/test/cxx11_eventcount.o ./eigen-3.4.0/unsupported/test/cxx11_eventcount.su ./eigen-3.4.0/unsupported/test/cxx11_maxsizevector.d ./eigen-3.4.0/unsupported/test/cxx11_maxsizevector.o ./eigen-3.4.0/unsupported/test/cxx11_maxsizevector.su ./eigen-3.4.0/unsupported/test/cxx11_meta.d ./eigen-3.4.0/unsupported/test/cxx11_meta.o ./eigen-3.4.0/unsupported/test/cxx11_meta.su ./eigen-3.4.0/unsupported/test/cxx11_non_blocking_thread_pool.d ./eigen-3.4.0/unsupported/test/cxx11_non_blocking_thread_pool.o ./eigen-3.4.0/unsupported/test/cxx11_non_blocking_thread_pool.su ./eigen-3.4.0/unsupported/test/cxx11_runqueue.d ./eigen-3.4.0/unsupported/test/cxx11_runqueue.o ./eigen-3.4.0/unsupported/test/cxx11_runqueue.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_argmax.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_argmax.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_argmax.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_argmax_sycl.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_argmax_sycl.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_argmax_sycl.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_assign.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_assign.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_assign.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_block_access.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_block_access.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_block_access.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_block_eval.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_block_eval.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_block_eval.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_block_io.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_block_io.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_block_io.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_broadcast_sycl.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_broadcast_sycl.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_broadcast_sycl.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_broadcasting.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_broadcasting.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_broadcasting.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_builtins_sycl.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_builtins_sycl.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_builtins_sycl.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_casts.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_casts.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_casts.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_chipping.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_chipping.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_chipping.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_chipping_sycl.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_chipping_sycl.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_chipping_sycl.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_comparisons.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_comparisons.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_comparisons.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_concatenation.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_concatenation.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_concatenation.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_concatenation_sycl.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_concatenation_sycl.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_concatenation_sycl.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_const.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_const.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_const.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_contract_sycl.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_contract_sycl.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_contract_sycl.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_contraction.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_contraction.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_contraction.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_convolution.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_convolution.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_convolution.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_convolution_sycl.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_convolution_sycl.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_convolution_sycl.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_custom_index.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_custom_index.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_custom_index.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_custom_op.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_custom_op.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_custom_op.su
	-$(RM) ./eigen-3.4.0/unsupported/test/cxx11_tensor_custom_op_sycl.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_custom_op_sycl.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_custom_op_sycl.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_device_sycl.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_device_sycl.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_device_sycl.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_dimension.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_dimension.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_dimension.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_empty.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_empty.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_empty.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_executor.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_executor.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_executor.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_expr.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_expr.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_expr.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_fft.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_fft.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_fft.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_fixed_size.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_fixed_size.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_fixed_size.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_forced_eval.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_forced_eval.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_forced_eval.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_forced_eval_sycl.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_forced_eval_sycl.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_forced_eval_sycl.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_generator.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_generator.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_generator.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_generator_sycl.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_generator_sycl.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_generator_sycl.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_ifft.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_ifft.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_ifft.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_image_op_sycl.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_image_op_sycl.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_image_op_sycl.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_image_patch.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_image_patch.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_image_patch.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_image_patch_sycl.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_image_patch_sycl.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_image_patch_sycl.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_index_list.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_index_list.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_index_list.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_inflation.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_inflation.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_inflation.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_inflation_sycl.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_inflation_sycl.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_inflation_sycl.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_intdiv.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_intdiv.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_intdiv.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_io.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_io.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_io.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_layout_swap.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_layout_swap.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_layout_swap.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_layout_swap_sycl.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_layout_swap_sycl.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_layout_swap_sycl.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_lvalue.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_lvalue.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_lvalue.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_map.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_map.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_map.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_math.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_math.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_math.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_math_sycl.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_math_sycl.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_math_sycl.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_mixed_indices.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_mixed_indices.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_mixed_indices.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_morphing.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_morphing.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_morphing.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_morphing_sycl.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_morphing_sycl.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_morphing_sycl.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_move.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_move.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_move.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_notification.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_notification.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_notification.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_of_complex.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_of_complex.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_of_complex.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_of_const_values.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_of_const_values.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_of_const_values.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_of_strings.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_of_strings.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_of_strings.su
	-$(RM) ./eigen-3.4.0/unsupported/test/cxx11_tensor_padding.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_padding.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_padding.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_padding_sycl.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_padding_sycl.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_padding_sycl.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_patch.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_patch.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_patch.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_patch_sycl.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_patch_sycl.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_patch_sycl.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_random.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_random.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_random.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_random_sycl.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_random_sycl.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_random_sycl.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_reduction.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_reduction.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_reduction.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_reduction_sycl.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_reduction_sycl.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_reduction_sycl.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_ref.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_ref.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_ref.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_reverse.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_reverse.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_reverse.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_reverse_sycl.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_reverse_sycl.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_reverse_sycl.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_roundings.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_roundings.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_roundings.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_scan.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_scan.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_scan.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_scan_sycl.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_scan_sycl.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_scan_sycl.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_shuffling.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_shuffling.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_shuffling.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_shuffling_sycl.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_shuffling_sycl.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_shuffling_sycl.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_simple.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_simple.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_simple.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_striding.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_striding.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_striding.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_striding_sycl.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_striding_sycl.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_striding_sycl.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_sugar.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_sugar.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_sugar.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_sycl.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_sycl.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_sycl.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_symmetry.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_symmetry.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_symmetry.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_thread_local.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_thread_local.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_thread_local.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_thread_pool.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_thread_pool.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_thread_pool.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_trace.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_trace.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_trace.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_uint128.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_uint128.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_uint128.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_volume_patch.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_volume_patch.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_volume_patch.su ./eigen-3.4.0/unsupported/test/cxx11_tensor_volume_patch_sycl.d ./eigen-3.4.0/unsupported/test/cxx11_tensor_volume_patch_sycl.o ./eigen-3.4.0/unsupported/test/cxx11_tensor_volume_patch_sycl.su ./eigen-3.4.0/unsupported/test/dgmres.d ./eigen-3.4.0/unsupported/test/dgmres.o ./eigen-3.4.0/unsupported/test/dgmres.su ./eigen-3.4.0/unsupported/test/forward_adolc.d ./eigen-3.4.0/unsupported/test/forward_adolc.o ./eigen-3.4.0/unsupported/test/forward_adolc.su ./eigen-3.4.0/unsupported/test/gmres.d ./eigen-3.4.0/unsupported/test/gmres.o ./eigen-3.4.0/unsupported/test/gmres.su ./eigen-3.4.0/unsupported/test/idrs.d ./eigen-3.4.0/unsupported/test/idrs.o ./eigen-3.4.0/unsupported/test/idrs.su ./eigen-3.4.0/unsupported/test/kronecker_product.d ./eigen-3.4.0/unsupported/test/kronecker_product.o ./eigen-3.4.0/unsupported/test/kronecker_product.su ./eigen-3.4.0/unsupported/test/levenberg_marquardt.d ./eigen-3.4.0/unsupported/test/levenberg_marquardt.o ./eigen-3.4.0/unsupported/test/levenberg_marquardt.su ./eigen-3.4.0/unsupported/test/matrix_exponential.d ./eigen-3.4.0/unsupported/test/matrix_exponential.o ./eigen-3.4.0/unsupported/test/matrix_exponential.su ./eigen-3.4.0/unsupported/test/matrix_function.d ./eigen-3.4.0/unsupported/test/matrix_function.o ./eigen-3.4.0/unsupported/test/matrix_function.su ./eigen-3.4.0/unsupported/test/matrix_power.d ./eigen-3.4.0/unsupported/test/matrix_power.o ./eigen-3.4.0/unsupported/test/matrix_power.su
	-$(RM) ./eigen-3.4.0/unsupported/test/matrix_square_root.d ./eigen-3.4.0/unsupported/test/matrix_square_root.o ./eigen-3.4.0/unsupported/test/matrix_square_root.su ./eigen-3.4.0/unsupported/test/minres.d ./eigen-3.4.0/unsupported/test/minres.o ./eigen-3.4.0/unsupported/test/minres.su ./eigen-3.4.0/unsupported/test/mpreal_support.d ./eigen-3.4.0/unsupported/test/mpreal_support.o ./eigen-3.4.0/unsupported/test/mpreal_support.su ./eigen-3.4.0/unsupported/test/openglsupport.d ./eigen-3.4.0/unsupported/test/openglsupport.o ./eigen-3.4.0/unsupported/test/openglsupport.su ./eigen-3.4.0/unsupported/test/polynomialsolver.d ./eigen-3.4.0/unsupported/test/polynomialsolver.o ./eigen-3.4.0/unsupported/test/polynomialsolver.su ./eigen-3.4.0/unsupported/test/polynomialutils.d ./eigen-3.4.0/unsupported/test/polynomialutils.o ./eigen-3.4.0/unsupported/test/polynomialutils.su ./eigen-3.4.0/unsupported/test/sparse_extra.d ./eigen-3.4.0/unsupported/test/sparse_extra.o ./eigen-3.4.0/unsupported/test/sparse_extra.su ./eigen-3.4.0/unsupported/test/special_functions.d ./eigen-3.4.0/unsupported/test/special_functions.o ./eigen-3.4.0/unsupported/test/special_functions.su ./eigen-3.4.0/unsupported/test/special_packetmath.d ./eigen-3.4.0/unsupported/test/special_packetmath.o ./eigen-3.4.0/unsupported/test/special_packetmath.su ./eigen-3.4.0/unsupported/test/splines.d ./eigen-3.4.0/unsupported/test/splines.o ./eigen-3.4.0/unsupported/test/splines.su

.PHONY: clean-eigen-2d-3-2e-4-2e-0-2f-unsupported-2f-test

